### ISSUE TITLE
Update and check documentation for plugins

### ISSUE THREAD

**Issue by numeredev** [numere-org/NumeRe#195]
### DESCRIPTION
**Is your change request related to a problem? Please describe.**
The documentation for plugins might be wrong of outdated. Especially regarding procedure flags, which seem to require `macro` to function correctly.

**Describe the solution you'd like**
Check and update the documentation correspondingly.

**Describe possible alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered, if any.

**Additional context**

(*Do not write below this line*)

-----------------------------------------------------
### ANALYSIS
Evaluate the functionalities for plugins especially for non-string expressions. Those will require most probably a `macro` flag. Update the documentation files (for procedures and for plugins) to reflect that.

### IMPLEMENTATION STEPS
(*see also our [Wiki for implementation guidelines](https://github.com/numeredev/NumeRe/wiki/HowTo:-Contribute-Code)*)
- Implement the necessary changes in a new branch created here on GitHub
- Test your implementation

### DOCUMENTATION STEPS
(*see also our [Wiki for further information](https://github.com/numeredev/NumeRe/wiki/HowTo:-Create-Language-Strings)*)
- Update the changes log
- Add comments to your implementation
- Add Doxygen documentation comments
- Create or update the documentation articles (`*.NHLP` and `*.NDB` files, if needed)
- Update the language strings (`*.NLNG` files, if needed)

### PULL REQUEST
- Create a pull request for your changes
- Fill out the template
- Assign @numere-org/maintainers as reviewers

**Comment by numeredev** [comment]
It's not only about updating the documentation, but also about making everything more systematic:

- [ ] `<EXPRESSION>` should be made a legacy tag and superseded with `<EXPRSTRING>`, which converts the expression to a simple string. The latter will make the `macro`  flag of procedures superfluous
- [ ] All tags should use `toInternalString()` for their string conversions to get the quotation marks correct
- [ ] There should be something like `<PARAMLIST>`, which passes the parameters and their values as a key-value list (this does not have to work in all possible cases, only the ones typically handled by the `CommandLineParser` class. Special cases can still fall back to the original `<PARAMSTRING>` tag
- [ ] Reflect those changes in their respective documentation (especially `macro` within the `procedure` article)
