### ISSUE TITLE
Function for accessing the user's current language

### ISSUE THREAD

**Issue by numeredev** [numere-org/NumeRe#32]
### DESCRIPTION
**What does your feature request improve on? Please describe.**
Writing generic packages require now that we either create that in English only or let the user decide upon the used language (which requires additional overhead). Having a function to access the user's installed language, would make this a bit easier.

**Describe the solution you'd like**
Create a function `getuilang() -> STR`, which shall return the language codes like `de-DE` or `en-GB` of the current used and installed language.

**Additional context**

(*Do not write below this line*)

-----------------------------------------------------
### ANALYSIS
- [x] Create a new language string in `main.nlng`, e.g. `LANGUAGE=en-GB` or `LANGUAGE=de-DE`
- [x] Create a string function `getuilang()` as `static StringVector strfnc_getuilang(StringFuncArgs& funcArgs)`, register that in `static std::map<std::string, StringFuncHandle> getStringFuncHandles()` (both in `kernel/core/strings/stringfunctions.hpp`) as `StringFuncHandle(NOARGS, strfnc_getuilang, false)`
- [x] Search for `"getversioninfo"` in the code base and add `"getuilang"` to these locations
- [x] Add `getuilang` to `common/syntaxelements.nlang`
- [x] Add `getuilang` to the language files `*/numere.nlang` as well as the search data base `*/find.ndb`

### IMPLEMENTATION STEPS
(*see also our [Wiki for implementation guidelines](https://github.com/numeredev/NumeRe/wiki/HowTo:-Contribute-Code)*)
- Implement the necessary changes in a new branch created here on GitHub
- Test your implementation

### DOCUMENTATION STEPS
(*see also our [Wiki for further information](https://github.com/numeredev/NumeRe/wiki/HowTo:-Create-Language-Strings)*)
- Update the changes log
- Add comments to your implementation
- Add Doxygen documentation comments
- Create or update the documentation articles (`*.NHLP` and `*.NDB` files, if needed)
- Update the language strings (`*.NLNG` files, if needed)

### PULL REQUEST
- Create a pull request for your changes
- Fill out the template
- Assign @numere-org/maintainers as reviewers
